name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    uses: archtenet/platform-infra/.github/workflows/service-ci.yml@main
    with:
      service-name: user-bff
      helm-path: user-bff/helm
    secrets: inherit
